### ISSUE TITLE
Überarbeitung der Suchansicht

### ISSUE THREAD

**Issue by baerlach-git** [hpi-swa-lab/BP2021RH1#143]
Problem: Die verschiedenen Suchkategorien sind nicht unbedingt sinnvoll geordnet. Die Zeitkategorien sollten ganz oben stehen und generell sollten die Kategorien nach Relevanz geordnet sein. Manche Kategorien enthalten nur wenige Bilder. Die Suche soll intuitiver gestaltet werden. Eventuell könnte ein Zeitstrahl eingefügt werden (mit "von" und "bis" Eingabefeldern).

Aufgabe:
- Erstellung von zwei low fidelity Prototypen

Stand:
- [x] Prototyp 1
- [ ] Prototyp2

**Comment by rheaSPK** [comment]
Erster Prototyp: https://www.figma.com/file/XSZByFO0muiaQa3wSHVvrM/Ahrensfeld-basic-structure?node-id=0%3A1
