### ISSUE TITLE
Bilder mit Text verbinden

### ISSUE THREAD

**Issue by DavidSchroschk** [hpi-swa-lab/BP2021RH1#170]
- [ ] Interface um zu einem/ mehreren Bilden einen Link zu einen (/mehreren) Text(en) (auch Bilder) hinzuzufügen/ anders herum
- [ ] Verlinkte Texte bei Bildern gut lesbar anzeigen

**Comment by rheaSPK** [comment]
Bitte die Bilder nicht im Zwischenspeicher hinzufügen sondern auf localstorage, da überlebt das ggf auch einen Neustart. Falls eh nicht schon angedacht
