### ISSUE TITLE
Kuratorensuche Nicht Getaggte Bilder

### ISSUE THREAD

**Issue by DavidSchroschk** [hpi-swa-lab/BP2021RH1#186]
- [ ] Kuratoren sollen die Möglichkeit haben innerhalb von Archiven nach nicht getaggten Bilden filtern zu können
- [ ] Möglichkeit für verschiedene Tag-Typen zu filtern
- [ ] In Suche eingebaut

### Offene Fragen
- Extra View?
- andere Vergleichsoperatoren? ("mehr als 3 Personen")
- Suchsyntax

**Comment by baerlach-git** [comment]
in #545 enthalten
