### ISSUE TITLE
Bulk Edit Collections

### ISSUE THREAD

**Issue by DavidSchroschk** [hpi-swa-lab/BP2021RH1#188]
- [ ] Beim Bulk Edit soll es möglich sein alles ausgewählten Bilder zu Collection(s) hinzuzufügen

**Comment by olschulz** [comment]
this will be unnecessary since we've decided to get rid of collections in the near future

**Comment by MariusDoe** [comment]
Reopened because Werner wanted to have this as a more comfortable temporary solution.
