### ISSUE TITLE
Use SVG icons instead of Font icons

### ISSUE THREAD

**Issue by MariusDoe** [hpi-swa-lab/BP2021RH1#248]
Currently, a mixture of e. g. `<Icon>delete</Icon>` (Font icon) and `<Delete />` (SVG icon) is used. [Only SVG icons should be used](https://mui.com/material-ui/icons/#font-vs-svg-which-approach-to-use).

**Comment by olschulz** [comment]
Should I fix that in the vite branch? I have to change a bunch of icons and icon imports there anyways.
