### ISSUE TITLE
Improve i18n usage

### ISSUE THREAD

**Issue by MariusDoe** [hpi-swa-lab/BP2021RH1#276]
`i18next` has support for [interpolation](https://www.i18next.com/translation-function/interpolation), [formatting](https://www.i18next.com/translation-function/formatting) and [plurals](https://www.i18next.com/translation-function/plurals). While we do use interpolation, we don't make use of the other two. This results in really inconsistent code and results:
https://github.com/hpi-swa-lab/BP2021RH1/blob/c3d13e73e730e2bd71d69d62673d3cafa2c00021/projects/bp-gallery/src/shared/locales/de.json#L80
https://github.com/hpi-swa-lab/BP2021RH1/blob/c3d13e73e730e2bd71d69d62673d3cafa2c00021/projects/bp-gallery/src/shared/locales/de.json#L145-L147
![image](https://user-images.githubusercontent.com/41512063/220672568-18be8846-9f75-4c47-9c99-a55cff5a70f8.png)
The last one could be `15.222 Bilder` by using the formatting and plurals features.

**Comment by olschulz** [comment]
Also, seems like i18n debug mode is enabled even in production. Console:
![image](https://user-images.githubusercontent.com/64468276/220700934-fd4cebd9-8574-47f7-b6bb-302b46694910.png)
