### ISSUE TITLE
Use Mui Theme for coloring buttons

### ISSUE THREAD

**Issue by MariusDoe** [hpi-swa-lab/BP2021RH1#288]
Use Mui's [Theming](https://mui.com/material-ui/customization/theming/) to change the primary color and then use `color='primary'` instead of manually providing the hex code from `style.scss`.

**Comment by olschulz** [comment]
Maybe replace the mui buttons with our own tailwind buttons and add our own colors like this?
![image](https://user-images.githubusercontent.com/64468276/222775568-05ee2c96-ca06-4944-9b83-f090d1a40930.png)
We can use our colors like normal tailwind colors then, which would definitely help with having an uniform design/layout
