### ISSUE TITLE
Alter Stand der Website wird geladen

### ISSUE THREAD

**Issue by LinoH5** [hpi-swa-lab/BP2021RH1#295]
Bei Zugriffen auf die Website über `www.harz-history.de`, oder `bilder.bad-harzburg-stiftung.de` wird die komplette Website in ihrem alten Stand, von vor der Einführung der neuen Stöbernseite, des neuen Bild des Tages Cardlayout und weiteren Commits geladen.

Ein Neuladen der Seite, oder aber ein direkter Zugriff auf sie über `bilder.bad-harzburg-stiftung.de/start` zeigt die neuste Version der Website.

**Comment by olschulz** [comment]
@LinoH5 Ist es bei dir immernoch broken? Ich kann's jetzt nicht mehr reproduzieren jedenfalls. War eventuell wirklich nur irgendein DNS kram

**Comment by LinoH5** [comment]
Ich kann es mittlerweile auch nicht mehr reproduzieren. Würde es dementsprechend schließen, und es weiter im Auge behalten.
