### ISSUE TITLE
Auf der Startseite sollte es einen auffälligen Verweis auf die Stöbern-Seite geben

### ISSUE THREAD

**Issue by baerlach-git** [hpi-swa-lab/BP2021RH1#308]
Im ursprünglichen Design war unter dem Bild des Tages ein großer roter Button vorgesehen, der auf die Stöbern-Seite verweist. Da einige Nutzer und Kuratoren die Stöbern-Seite noch nicht kannten, sollte dieser wieder eingeführt werden. Der Schriftzug in der Top-Bar alleine ist zu unscheinbar.

**Comment by MariusDoe** [comment]
Relevant: #374
