### ISSUE TITLE
Der Like-Button für das Bild des Tages sollte direkt auf der Startseite sichtbar sein, ohne dass man in die PictureView wechseln muss

### ISSUE THREAD

**Issue by baerlach-git** [hpi-swa-lab/BP2021RH1#310]
Extra auf das Bild klicken zu müssen um das Bild des Tages zu liken ist ein unnötiger Zwischenschritt. Wenn man das Bild des Tages direkt liken könnte, würden wir vielleicht mehr Likes für dieses bekommen und könnten Leute vielleicht generell mehr auf die Like-Funktion aufmerksam machen, da einigen noch nicht bewusst ist, dass diese überhaupt existiert.

**Comment by MariusDoe** [comment]
This was implemented in #416, correct?

**Comment by MariusDoe** [comment]
see above
