### ISSUE TITLE
Archive sollten strukturiert werden können

### ISSUE THREAD

**Issue by baerlach-git** [hpi-swa-lab/BP2021RH1#317]
Manche Archive enthalten sehr viele Bilder wie z.B. das Herbert-Ahrens-Archiv mit über 16000 Bildern. Dadurch werden sie extrem unübersichtlich und man kann nicht mehr richtig in ihnen stöbern. Es sollte eine Möglichkeit geben diese irgendwie zu struktieren, dies könnte auch Kuratoren dabei helfen ihre Sammlungen auf der Seite ähnlich zu ordnen, wie sie es schon analog machen.

**Comment by MariusDoe** [comment]
Relevant: #323

**Comment by MariusDoe** [comment]
Duplicate of #323
