### ISSUE TITLE
Erweiterung der Suchoptionen (Archive, Datum,...)

### ISSUE THREAD

**Issue by LinoH5** [hpi-swa-lab/BP2021RH1#327]
- ~Ermöglichen die Suche nach Archiven auszuteilen~ Es ist jetzt schon möglich nach Archiven zu suchen, bzw. wird das Archiv eines Bildes in die Suche mit einbezogen. Außerdem ist dieser Aspekt quasi eine Überschneidung mit #384 
- Ermöglichen die Suche auf bestimmte Zeitspannen von einem Tag/Monat/Jahr bis zu einem anderen Tag/Monat/Jahr festzulegen
- ~Explorieren weiterer Optionen, die interessant wären~

**Comment by baerlach-git** [comment]
will be implemented through #545 and #546
