### ISSUE TITLE
Bilder auf einer Landkarte aufgeschlüsselt darstellen

### ISSUE THREAD

**Issue by LinoH5** [hpi-swa-lab/BP2021RH1#330]
- Bilder auf einer zoombaren Karte nach ihrer Ortstags darstellen
- Beim zoomen Tags feiner bzw. grober aufschlüsseln und deren Anzahl entsprechend anzeigen

**Comment by MariusDoe** [comment]
Relevant: #349

**Comment by LinoH5** [comment]
Closed in #592
