### ISSUE TITLE
Zurückspringen auf die Stöbernseite erfolgt immer nach ganz oben auf der Stöbernseite

### ISSUE THREAD

**Issue by LinoH5** [hpi-swa-lab/BP2021RH1#338]
- Auf der Stöbernseite an die Stelle zurückzuspringen an der man in eine neue View navigiert hat
- Momentan springt man immer zum Start der Stöbernseite und muss dann wieder an die entsprechende Stelle scrollen

**Comment by MariusDoe** [comment]
Hackday: mglw. kann das Problem für alle `ScrollContainer` gefixt werden, indem sich die Position in dem`history` state gespeichert wird. Damit kann am Hackday herumexperimentiert werden.
