### ISSUE TITLE
Bilder sollten Gruppiert werden können.

### ISSUE THREAD

**Issue by baerlach-git** [hpi-swa-lab/BP2021RH1#359]
Das Gruppieren von Bildern könnte zum Beispiel benutzt werden, um Bildduplikate zusammenzufassen, sodass diese nicht die Bildübersicht überschwemmen sondern nur ein Symbol bzw. eine Bildvorschau pro Gruppe von Duplikaten angezeigt wird. Durch Klicken der Gruppe sollte dann eine Ansicht für diese Bildgruppe geöffnet werden.

**Comment by MariusDoe** [comment]
Duplicate of #324
