### ISSUE TITLE
Nutzerumfragen implementieren

### ISSUE THREAD

**Issue by baerlach-git** [hpi-swa-lab/BP2021RH1#365]
Um zusätzliche Nutzerdaten zu generieren, gerade wenn es um Fragen geht, die nicht direkt aus der Browserhistorie via Matomo entnommen werden können, könnten wir es möglich machen auf der Seite Nutzerumfragen durchzuführen. Dies wäre durch eine Anpassung des Kontaktformulars und der zugehörigen API schnell und leicht umsetzbar.

**Comment by MariusDoe** [comment]
Relevant: #332
