### ISSUE TITLE
Add Cache-Control config

### ISSUE THREAD

**Issue by MariusDoe** [hpi-swa-lab/BP2021RH1#437]
Currently, browser [cache busting](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#caching_static_assets_with_cache_busting) is working for our assets (js, css, etc.) since vite/rollup does that automatically:
<img src="https://user-images.githubusercontent.com/41512063/233834246-ce4bfb7d-ed19-4376-b9d7-0924dbebdcec.png" alt="cache-busting" height="300"/>
However, the `index.html` has no browser cache configuration, i. e. no HTTP header `Cache-Control` is given by the server (nginx).
This results in the `index.html` being cached by the browser (seemingly) indefinitely, rendering the cache busting for the assets useless since it depends on a change in `index.html` being recognized by the browser. A solution is to add the relevant header to the nginx config as described in the linked article. In doing so, `index.html` and the assets should get different headers (again, as described in the article).

Relevant: #346 (@olschulz)

**Comment by olschulz** [comment]
Was added to the nginx config of staging and production and should be fixed now. Unfortunately some users will still have the cached version that doesn't tell them that it shouldn't be cached for some time.
